# Generated by Django 3.1.5 on 2021-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='dateformed',
            field=models.CharField(default=1997, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(default=1998, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='name',
            field=models.CharField(default=1997, max_length=100),
            preserve_default=False,
        ),
    ]
