# Generated by Django 3.1.5 on 2021-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_band_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='SimilarBands',
            field=models.ManyToManyField(to='main_app.SimilarBand'),
        ),
    ]
