# Generated by Django 3.1.5 on 2021-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210204_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarband',
            name='genre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
