# Generated by Django 3.1.5 on 2021-02-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_similarband_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='SimilarBands',
            new_name='similarbands',
        ),
    ]
